 const menulist=[
     {
         title:'首页',
         key:'/home',
         icon:'home'
     },
     {
        title:'设置',
        key:'/setting',
        icon:'setting',
        children:[
            {
                title:'更新时间',
                key:'/setting/update',
                icon:'clock-circle'
            },
            {
                title:'回收时间',
                key:'/setting/delete',
                icon:'clock-circle'
            }
        ]
    },
    {
        title:'用户管理',
        key:"/user",
        icon:'user',
    },
    {
        title:'全部文件',
        key:'/files',
        icon:'file',
        children:[
            {
                title:'图片',
                key:'/files/picture',
                icon:'picture'
            },
            {
                title:'文档',
                key:'/files/folder',
                icon:'folder'
            },
            {
                title:'视频',
                key:'/files/video',
                icon:'video-camera'
            },
            {
                title:'音乐',
                key:'/files/music',
                icon:'sound'
            },
            {
                title:'其他',
                key:'/files/other',
                icon:'small-dash'
            },
        ]
    },
    {
        title:'历史记录',
        key:'/history',
        icon:'history'
    },
    {
        title:'回收站',
        key:'/recycle',
        icon:'delete'
    },
 ]
 export default menulist